"""Generate PDF patrol brief for BTP officers using fpdf2."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from fpdf import FPDF


def generate_patrol_pdf(plan: dict[str, Any]) -> bytes:
    """Return a patrol brief as PDF bytes from an enforcement plan dict."""
    pdf = FPDF()
    pdf.set_margins(14, 14, 14)
    pdf.add_page()

    # Header bar
    pdf.set_fill_color(10, 10, 20)
    pdf.rect(0, 0, 210, 28, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_xy(14, 6)
    pdf.cell(0, 7, "ParkSentinel  -  Patrol Enforcement Brief", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(14)
    pdf.cell(
        0, 6,
        f"Bengaluru Traffic Police  |  {datetime.now().strftime('%d %b %Y, %H:%M')}  "
        f"|  AI-powered parking enforcement intelligence",
        ln=True,
    )
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(32)

    # Summary row
    items = plan.get("items", [])
    total_officers = plan.get("total_officers", 0)
    zones = plan.get("zones_count", len(items))
    est_km = plan.get("estimated_travel_km", 0.0)
    saved_pct = plan.get("time_saved_pct", 0.0)
    date_label = plan.get("date", datetime.now().strftime("%Y-%m-%d"))
    dist_source = plan.get("distance_source", "haversine")

    summary_cells = [
        ("Date", date_label),
        ("Zones", str(zones)),
        ("Officers", str(total_officers)),
        ("Route", f"{est_km:.1f} km"),
        ("Saved", f"{saved_pct:.1f}%"),
        ("Routing", dist_source),
    ]
    cell_w = (210 - 28) / len(summary_cells)
    for label, val in summary_cells:
        x = pdf.get_x()
        pdf.set_fill_color(240, 242, 248)
        pdf.cell(cell_w, 14, "", border=1, fill=True)
        pdf.set_xy(x + 2, pdf.get_y() + 1)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(cell_w - 4, 4, label, ln=False)
        pdf.set_xy(x + 2, pdf.get_y() + 4)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(cell_w - 4, 5, val, ln=False)
        pdf.set_xy(x + cell_w, pdf.get_y() - 5)

    pdf.ln(10)
    pdf.set_text_color(0, 0, 0)

    # Zone table header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(30, 30, 50)
    pdf.set_text_color(255, 255, 255)
    col_w = [8, 52, 14, 22, 30, 22, 34]
    headers = ["#", "Zone / Location", "CIS", "Class", "Top Violation", "Officers", "Shift"]
    for w, h in zip(col_w, headers):
        pdf.cell(w, 7, h, fill=True, align="C" if w < 20 else "L")
    pdf.ln()

    fill_colors = {
        "CRITICAL": (255, 235, 235), "HIGH": (255, 245, 230),
        "MODERATE": (255, 253, 225), "LOW": (235, 255, 240),
    }
    text_colors = {
        "CRITICAL": (180, 20, 20), "HIGH": (200, 70, 0),
        "MODERATE": (150, 100, 0), "LOW": (0, 120, 50),
    }

    pdf.set_font("Helvetica", "", 8)
    for i, item in enumerate(items):
        cls = item.get("classification", "LOW")
        fr, fg, fb = fill_colors.get(cls, (245, 245, 245))
        tr, tg, tb = text_colors.get(cls, (40, 40, 40))
        pdf.set_fill_color(fr, fg, fb)

        pdf.set_text_color(80, 80, 80)
        pdf.cell(col_w[0], 6, str(item.get("rank", i + 1)), fill=True, align="C")
        pdf.set_text_color(20, 20, 20)
        pdf.cell(col_w[1], 6, str(item.get("zone_name", ""))[:30], fill=True)
        pdf.set_text_color(tr, tg, tb)
        pdf.cell(col_w[2], 6, str(item.get("cis", "")), fill=True, align="C")
        pdf.cell(col_w[3], 6, cls, fill=True, align="C")
        pdf.set_text_color(50, 50, 50)
        viol = str(item.get("dominant_violation") or "-")[:18]
        pdf.cell(col_w[4], 6, viol, fill=True)
        pdf.cell(col_w[5], 6, str(item.get("recommended_officers", 1)), fill=True, align="C")
        pdf.cell(col_w[6], 6, str(item.get("recommended_shift", "")), fill=True)
        pdf.ln()
        pdf.set_text_color(0, 0, 0)

    # Footer note
    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0, 4,
        "Generated by ParkSentinel - the parking-enforcement intelligence layer designed for "
        "integration with ASTraM (BTP Actionable Intelligence for Sustainable Traffic Management). "
        f"Route optimised using OR-Tools VRP. Distance source: {dist_source}. "
        "Gridlock Hackathon 2.0.",
    )

    return bytes(pdf.output())
